# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # This checks for minor and major version updates every week
  - package-ecosystem: "cargo"
    directories:
      - "add-header"
      - "auth"
      - "dependent-header"
      - "dispatch-calls"
      - "headers"
      - "plugin-config"
      - "ticks"
      - "vm-start"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "antonengelhardt"
    assignees:
      - "antonengelhardt"
    commit-message:
      prefix: "chore(deps): update"
      include: "scope"
